In [1]:
# Langkah 1 - Import Library
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# Langkah 2 - Load Data
dataset = pd.read_csv('../assets/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
# Langkah 3 - Encoding Data Kategorikal
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
# Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
# Langkah 5 - Split Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Langkah 6 - Scaling Fitur
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Membuat Model ANN

In [10]:
# Langkah 1 - Inisiasi Model ANN
ann = tf.keras.models.Sequential()

In [11]:
# Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
# Langkah 3 - Membuat Hidden Layer Kedua
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
# Langkah 4 - Membuat Output Layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training Model

In [14]:
# Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
# Langkah 2 - Fitting Model
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 657us/step - accuracy: 0.7783 - loss: 0.5678
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7984 - loss: 0.4803
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - accuracy: 0.7929 - loss: 0.4652
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.8003 - loss: 0.4502
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.8004 - loss: 0.4340
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8142 - loss: 0.4177
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.8170 - loss: 0.4107
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8115 - loss: 0.4157
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.8100 - loss: 0.4138
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8047 - loss: 0.4111
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - accuracy: 0.8058 - loss: 0.4110
Epoch 12/100
250/25

In [16]:
# Modelkan Data Baru dan Buat Prediksi
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[False]]


In [17]:
# Prediksi Dengan Data Testing
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [18]:
# Cek Akurasi dan Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 195  210]]


0.861