<a href="https://colab.research.google.com/github/byannurcahyo/2241720134-ML-2024/blob/main/Feature%20Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Praktikum Mata Kuliah Machine Learning** :
## Byan Nur Cahyo / 2241720134 / TI-3D

# **Praktikum** :

## 1.Implementasi Normalisasi

In [ ]:
def norm_data(data):
  '''
  Melakukan normalisasi data.

  Parameters:
      data (list) : Data yang akan dinormalisasi

    Returns:
      data (list) : Data hasil normalisasi
  '''
  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)
  return data

#contoh penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)
print(n_data)
#output : [0.0, 0.25, 0.5, 0.75, 1.0]

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.array(data)
print('Data Asli')
print(data)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)
print('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


## 2.Implementasi Standard

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.array(data)
print('Data Asli')
print(data)

scaler =StandardScaler()
scaled = scaler.fit_transform(data)
print('Data Standarisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


## 3.Implementasi Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

transform_oe = oe.fit_transform(data)
print('Data Asli')
print(data)
print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


## 4.Implementasi One-Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

transform_ohe = ohe.fit_transform(data)
print('Data Asli')
print(data)
print('Data Transformasi One-Hot Encoding')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


## 5.Implementasi Dummy Variable Encoding

In [32]:
from sklearn.preprocessing import OneHotEncoder

de = OneHotEncoder(drop='first')

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

transform_de = de.fit_transform(data)
print('Data Asli')
print(data)
print('Data Transformasi One-Hot Encoding')
print(transform_de.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


## 6.Studi Kasus Ekstraksi Fitur dari Data Teks

In [ ]:
corpus = [
    'The house had a tiny little mouse',
    'The cat saw the mouse',
    'The mouse ran away from the house',
    'The cat finally ate the mouse',
    'The end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)

print('Hasil TF-IDF')
print(resp)

print('Hasil Token')
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


# **Tugas Praktikum** :

In [31]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/corpus.txt'

with open(file_path, 'r') as file:
    corpus = file.readlines()

from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)

print('Hasil TF-IDF')
print(resp)

print('Hasil Token')
print(vect.get_feature_names_out())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Hasil TF-IDF
  (0, 3)	1.0
  (1, 8)	0.31257907911644855
  (1, 7)	0.579262311604141
  (1, 12)	0.579262311604141
  (1, 6)	0.48083746527154797
  (2, 10)	0.7106281860049563
  (2, 2)	0.5898824226331707
  (2, 8)	0.3834661767662525
  (3, 1)	0.579262311604141
  (3, 9)	0.579262311604141
  (3, 8)	0.31257907911644855
  (3, 6)	0.48083746527154797
  (4, 0)	0.579262311604141
  (4, 5)	0.579262311604141
  (4, 2)	0.48083746527154797
  (4, 8)	0.31257907911644855
  (5, 11)	0.6606476647333884
  (5, 4)	0.6606476647333884
  (5, 8)	0.3564958992255601
Hasil Token
['ate' 'away' 'cat' 'corpus' 'end' 'finally' 'house' 'little' 'mouse'
 'ran' 'saw' 'story' 'tiny']
